### ISSUE TITLE
Using with Homebrew's libusb

### ISSUE THREAD

**Issue by matthewrankin** [kylelemons/gousb#15]
I'm not sure, but I'm guessing my problem relates to using Homebrew's libusb 1.0.19 on OS X. Here's what I get when trying to install lsusb:

```
$ cd ~/development/foss-projects/github.com/kylelemons/gousb
$ ./fixlibusb_darwin.sh /usr/local/include/libusb-1.0/libusb.h
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/c++/4.2.1
It looks like you've already run this script (/usr/local/include/libusb-1.0/libusb.h.orig exists)
$ go get -v github.com/kylelemons/gousb/lsusb
github.com/kylelemons/gousb/usb
# github.com/kylelemons/gousb/usb
../../../../go/src/github.com/kylelemons/gousb/usb/config.go:17:11: fatal error: 'libusb-1.0/libusb.h' file not found
 #include <libusb-1.0/libusb.h>
          ^
1 error generated.
```

**Comment by matthewrankin** [comment]
I've been able to successfully use [truveris's gousb fork][truveris] with the Homebrew installed libusb 1.0.

[truveris]: https://github.com/truveris/gousb

**Comment by tobyjaguar** [comment]
Any update on this? I just ran into the same thing...

I don't have a libusb-1.0 folder in /usr/local/lib
there is a libusb-1.0.dylib but no libusb-1.0

Any ideas here?

**Comment by matthewrankin** [comment]
@tobyjaguar The last time I tried using this package with [Homebrew][], I had to use the [truveris/gousb][truveris] fork of [kylelemons/gousb][kylelemons].

Since June 2015, I have been using [gotmc/libusb][gotmc], which I authored. 

[kylelemons]: https://github.com/kylelemons/gousb/
[gotmc]: https://github.com/gotmc/libusb/
[homebrew]: http://brew.sh
[truveris]: https://github.com/truveris/gousb

**Comment by zagrodzki** [comment]
@matthewrankin @tobyjaguar would you mind running this command for me on your system that has the Homebrew's libusb installed:
pkg-config --cflags libusb-1.0
If that works and shows an include path (-I/some/path...), then it would be beneficial to gousb to include the headers with pkg-config instead.

**Comment by matthewrankin** [comment]
Here's the `pkg-config` result from my MacBook Pro:

    $ pkg-config --cflags libusb-1.0
    -I/usr/local/Cellar/libusb/1.0.21/include/libusb-1.0

For USB with Go, I've been using https://github.com/gotmc/libusb, which has the following to work with Homebrew's libusb:

    // #cgo pkg-config: libusb-1.0
    // #include <libusb.h> 


**Full disclosure:** I'm the primary author of the https://github.com/gotmc/libusb library.

**Comment by tobyjaguar** [comment]
I can echo the same result:

pkg-config --cflags libusb-1.0

-I/usr/local/Cellar/libusb/1.0.20/include/libusb-1.0



thanks for looking into this...


toby



*--This message is intended for the sole use of the addressee, and may
contain information that is privileged, confidential, and exempt from
disclosure under applicable law. You are hereby notified that you may not
use, copy, disclose, or distribute to anyone the message or any information
contained in the message, and are strictly prohibited from disclosing,
copying, distributing, disseminating, or taking any other action against me
with regard to the information and the contents herein, including, but not
limited to my attached material, and/or the comments made about my attached
material or...any other "material" art transmitted via this account. The
foregoing prohibitions also apply to your employee, agent, student or any
personnel under your direction or control. The contents of this message are
private and legally privileged and confidential information, and the
violation of my personal privacy is punishable by law. UCC 1-103 1-308 ALL
RIGHTS RESERVED WITHOUT PREJUDICE ***If this message was received in error,
please advise the sender by reply email and delete this message. *

**Comment by zagrodzki** [comment]
Thanks. I think it should be a straightforward change to gousb. I'll prepare a branch.

In the meantime, @matthewrankin: was that issue the the only reason to implement your own library? I certainly hope not :) But in general, if you have thoughts on making gousb more useful that you implemented in your libraries, please share them.

From my side, I'm now working on a streaming interface that would allow higher throughput than current implementation. As far as I can tell, none (few?) of the Go bindings for libusb allow that, that aren't thin wrappers around C libusb.

**Comment by matthewrankin** [comment]
@zagrodzki No, that wasn't the only reason. There were some speed issues associated with connecting to a new USB device that caused me to implement the libusb library.

**Comment by zagrodzki** [comment]
@matthewrankin would you mind elaborating on the speed issues? If it's an issue that I could fix in gousb, I'd be happy to take a shot.

**Comment by zagrodzki** [comment]
#30 is out to address the include issue.

**Comment by zagrodzki** [comment]
This should be now fixed.

**Comment by matthewrankin** [comment]
@zagrodzki I'm not sure what the speed issue had been, but it appears to not be an issue at this point.
