### ISSUE TITLE
Writing or copying files to USB devices

### ISSUE THREAD

**Issue by EwanValentine** [kylelemons/gousb#20]
Hi there, 

I have the following range loop, I'm attempting to write a file output to each device. Is this possible? 

```
for _, dev := range devs {
        // Once the device has been selected from ListDevices, it is opened
        // and can be interacted with.

        conf, err := dev.ActiveConfig()
        if err != nil {
            log.Fatalf("Cannot get active config: %s", err)
        }

        write, err := dev.OpenEndpoint(conf, uint8(0),
            uint8(0), uint8(2)|uint8(usb.ENDPOINT_DIR_OUT))
        if err != nil {
            log.Fatalf("Failed to open write endpoint: %s", err)
        }

        write.Write([]byte("test"))
}
```

**Comment by kylelemons** [comment]
What's the use case behind this?  Typically you have very specific devices
to talk to and they often need to be managed independently even if they are
performing the same tasks.

**Comment by EwanValentine** [comment]
I'm attempting to listen for new USB storage devices being attached, and transferring a file to them once detected. Is there a way of return the device path, perhaps, with this library? I couldn't see anything like that from the docs. I think I might have to try something different. I get what you mean about devices needing to be managed independently.

**Comment by kylelemons** [comment]
Are you planning on speaking the USB Mass Storage protocol to the device
raw and do the filesystem emulation yourself?  I would imagine that it
would be far more robust to let the OS manage and auto-mount devices and
then write the file to the filesystem.

**Comment by EwanValentine** [comment]
Yeah that's probably the best solution, I mean to let the OS handle all of that. But in order to handle it through the OS, I need to know the location of the new storage device. So I can use this library to figure out if there's a new device plugged in, but I don't know how to get the filepath for that device then. If that makes sense?

**Comment by kylelemons** [comment]
As far as I know there's no way to get that from the device itself, you
need the kernel for that.  I'd suggest watching the directories your OS
uses for auto mounting, watching dmesg, maybe there are some /sys or /proc
files that could help.  You might also be able to plug into udev or similar.
