### ISSUE TITLE
Partial data on timeouts

### ISSUE THREAD

**Issue by codido** [kylelemons/gousb#23]
Hi,

In case an error is returned from libusb_bulk_transfer or libusb_interrupt_transfer, cnt is disregarded and 0 is returned. However, partial data may have been transferred in case of a timeout error. From libusb's documentation:
Also check transferred when dealing with a timeout error code. libusb may have to split your transfer into a number of chunks to satisfy underlying O/S requirements, meaning that the timeout may expire after the first few chunks have completed. libusb is careful not to lose any data that may have been transferred; do not assume that timeout conditions indicate a complete lack of I/O.

Thanks,
Ido.

**Comment by codido** [comment]
libusb_bulk_transfer & libusb_interrupt_transfer are no longer being used, so this seems to be resolved.

**Comment by zagrodzki** [comment]
Actually not just yet - transfer() returns 0 on error

**Comment by zagrodzki** [comment]
but I'm working on it :) I'll update this issue when I think all places are correct and covered by tests.

**Comment by codido** [comment]
Sure thing, though looking at the documentation it seems like the status of partial asynchronous transfers will be set to LIBUSB_TRANSFER_COMPLETED:
http://libusb.sourceforge.net/api-1.0/group__asyncio.html#ga9fcb2aa23d342060ebda1d0cf7478856

Is this misleading and LIBUSB_TRANSFER_TIMED_OUT can still be returned with partial xfer data?

**Comment by zagrodzki** [comment]
I think so. It's still the case that a single transfer might be split up by the host into multiple transactions, and some of them might succeed before the transfer completes. Same with isochronous transfers where some packets are transmitted before the transfer times out. But I'm not really sure and I haven't dig through libusb sources to check. If you want to look for confirmation one way or another in libusb sources, that'd be welcome :)

**Comment by codido** [comment]
Skimming through the code, seems that you're right - libusb_bulk_transfer just uses the asynchronous functions, so the two seem to share the same behavior - LIBUSB_TRANSFER_TIMED_OUT may be returned with actual_length != 0.

**Comment by zagrodzki** [comment]
I believe this is now addressed.
