### ISSUE TITLE
Flexible array members (in libusb.h) not supported on arm-linux-gnueabihf (Raspberry Pi 3) with gcc 5.4

### ISSUE THREAD

**Issue by mikehamer** [kylelemons/gousb#49]
Not sure where else to make this comment.

When building for the Raspberry Pi 3 (arm-linux-gnueabihf) on *buntu 16.4LTS using gcc 5.4.0 (non-llvm, as far as I can tell) from the Ubuntu armhf repository, I needed to patch libusb-1.0.20 with the changes from the `fixlibusb_darwin.sh` script. After patching, everything works as expected.

**Comment by zagrodzki** [comment]
Thanks. I'm wondering if we should address this upstream in the libusb. Can you share the exact failing compiler output?

**Comment by zagrodzki** [comment]
although https://gcc.gnu.org/onlinedocs/gcc/Zero-Length.html explicitly says that 0-size structs are supported by GCC. So maybe it's a problem with gcc on your platform? It's unclear to me yet.

**Comment by mikehamer** [comment]
This is from a fresh install of xubuntu 16.04.2 on a Raspberry Pi 3, after having performed a full update, installed relevant packages from apt, and go from the golang.org download page.

```
$ go get github.com/kylelemons/gousb/usb
# github.com/kylelemons/gousb/usb
go/src/github.com/kylelemons/gousb/usb/libusb.go:362: C.struct_libusb_transfer literal.iso_packet_desc undefined (type C.struct_libusb_transfer has no field or method iso_packet_desc)

$ go version
go version go1.8.1 linux/arm

$ gcc --version
gcc (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 
$ uname -a
Linux user-desktop 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l armv7l armv7l GNU/Linux

$ apt show libusb-1.0-0-dev
Package: libusb-1.0-0-dev
Version: 2:1.0.20-1
Priority: optional
Section: libdevel
Source: libusb-1.0
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Aurelien Jarno <aurel32@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 205 kB
Depends: libusb-1.0-0 (= 2:1.0.20-1)
Recommends: libusb-1.0-doc
Homepage: http://www.libusb.info
Supported: 9m
Download-Size: 53.9 kB
APT-Manual-Installed: yes
APT-Sources: http://ports.ubuntu.com xenial/main armhf Packages
Description: userspace USB programming library development files Library for programming USB applications without the knowledge of Linux kernel internals.
```

Note that the same error occurs when using libusb master, and is only solved by changing size-0 arrays to size-1 arrays in `libusb.h` (as is done by `fixlibusb_darwin.sh`).

**Comment by mikehamer** [comment]
Sorry, my mistake:

Note that the same error occurs when using libusb master, and is only solved by **changing flexible array members** ( eg. iso_packet_desc[ ] ) to size-1 arrays in `libusb.h`.

Which makes me think that it is being compiled in C90 mode. But:
```
$ gcc -dM -E - < /dev/null | grep __STDC_VERSION__
#define __STDC_VERSION__ 201112L
```

**Comment by mikehamer** [comment]
And there is nothing in the go build output that would suggest `-std=c90` or `-ansi` or any such flag is being used:

```
$ go build -n
#
# github.com/kylelemons/gousb/usb
#
 
mkdir -p $WORK/github.com/kylelemons/gousb/usb/_obj/
mkdir -p $WORK/github.com/kylelemons/gousb/
cd /home/idsc/go/src/github.com/kylelemons/gousb/usb
pkg-config --cflags libusb-1.0
pkg-config --libs libusb-1.0
CGO_LDFLAGS="-g" "-O2" /usr/local/go/pkg/tool/linux_arm/cgo -objdir $WORK/github.com/kylelemons/gousb/usb/_obj/ -importpath github.com/kylelemons/gousb/usb -- -I $WORK/github.com/kylelemons/gousb/usb/_obj/ -g -O2 constants.go error.go libusb.go
gcc -I . -fPIC -marm -pthread -fmessage-length=0 -I $WORK/github.com/kylelemons/gousb/usb/_obj/ -g -O2 -o $WORK/github.com/kylelemons/gousb/usb/_obj/_cgo_export.o -c $WORK/github.com/kylelemons/gousb/usb/_obj/_cgo_export.c
gcc -I . -fPIC -marm -pthread -fmessage-length=0 -I $WORK/github.com/kylelemons/gousb/usb/_obj/ -g -O2 -o $WORK/github.com/kylelemons/gousb/usb/_obj/constants.cgo2.o -c $WORK/github.com/kylelemons/gousb/usb/_obj/constants.cgo2.c
gcc -I . -fPIC -marm -pthread -fmessage-length=0 -I $WORK/github.com/kylelemons/gousb/usb/_obj/ -g -O2 -o $WORK/github.com/kylelemons/gousb/usb/_obj/error.cgo2.o -c $WORK/github.com/kylelemons/gousb/usb/_obj/error.cgo2.c
gcc -I . -fPIC -marm -pthread -fmessage-length=0 -I $WORK/github.com/kylelemons/gousb/usb/_obj/ -g -O2 -o $WORK/github.com/kylelemons/gousb/usb/_obj/libusb.cgo2.o -c $WORK/github.com/kylelemons/gousb/usb/_obj/libusb.cgo2.c
gcc -I . -fPIC -marm -pthread -fmessage-length=0 -I $WORK/github.com/kylelemons/gousb/usb/_obj/ -g -O2 -o $WORK/github.com/kylelemons/gousb/usb/_obj/transfer.o -c ./transfer.c
gcc -I . -fPIC -marm -pthread -fmessage-length=0 -I $WORK/github.com/kylelemons/gousb/usb/_obj/ -g -O2 -o $WORK/github.com/kylelemons/gousb/usb/_obj/_cgo_main.o -c $WORK/github.com/kylelemons/gousb/usb/_obj/_cgo_main.c
gcc -I . -fPIC -marm -pthread -fmessage-length=0 -o $WORK/github.com/kylelemons/gousb/usb/_obj/_cgo_.o $WORK/github.com/kylelemons/gousb/usb/_obj/_cgo_main.o $WORK/github.com/kylelemons/gousb/usb/_obj/_cgo_export.o $WORK/github.com/kylelemons/gousb/usb/_obj/constants.cgo2.o $WORK/github.com/kylelemons/gousb/usb/_obj/error.cgo2.o $WORK/github.com/kylelemons/gousb/usb/_obj/libusb.cgo2.o $WORK/github.com/kylelemons/gousb/usb/_obj/transfer.o -g -O2 -pie
/usr/local/go/pkg/tool/linux_arm/cgo -dynpackage usb -dynimport $WORK/github.com/kylelemons/gousb/usb/_obj/_cgo_.o -dynout $WORK/github.com/kylelemons/gousb/usb/_obj/_cgo_import.go
gcc -I . -fPIC -marm -pthread -fmessage-length=0 -o $WORK/github.com/kylelemons/gousb/usb/_obj/_all.o $WORK/github.com/kylelemons/gousb/usb/_obj/_cgo_export.o $WORK/github.com/kylelemons/gousb/usb/_obj/constants.cgo2.o $WORK/github.com/kylelemons/gousb/usb/_obj/error.cgo2.o $WORK/github.com/kylelemons/gousb/usb/_obj/libusb.cgo2.o $WORK/github.com/kylelemons/gousb/usb/_obj/transfer.o -g -O2 -Wl,-r -nostdlib -Wl,--build-id=none
/usr/local/go/pkg/tool/linux_arm/compile -o $WORK/github.com/kylelemons/gousb/usb.a -trimpath $WORK -p github.com/kylelemons/gousb/usb -buildid fbd3d1741d25b00daebdb54f73e8f43bb4ce183d -D _/home/idsc/go/src/github.com/kylelemons/gousb/usb -I $WORK -pack ./config.go ./debug.go ./descriptor.go ./device.go ./endpoint.go ./misc.go ./transfer.go ./usb.go $WORK/github.com/kylelemons/gousb/usb/_obj/_cgo_gotypes.go $WORK/github.com/kylelemons/gousb/usb/_obj/constants.cgo1.go $WORK/github.com/kylelemons/gousb/usb/_obj/error.cgo1.go $WORK/github.com/kylelemons/gousb/usb/_obj/libusb.cgo1.go $WORK/github.com/kylelemons/gousb/usb/_obj/_cgo_import.go
pack r $WORK/github.com/kylelemons/gousb/usb.a $WORK/github.com/kylelemons/gousb/usb/_obj/_all.o # internal
```

**Comment by zagrodzki** [comment]
Thanks, that's helpful. I'll see if I can replicate the issue on an x86_64 with the same setup.

In the meantime, would you mind trying something similar to this:
https://github.com/bazelbuild/rules_go/blob/master/examples/cgo/cc_dependency/c_version.c
with a trivial go code that would just call C.PrintCVersion()? That would at least confirm the default as used with cgo.

**Comment by mikehamer** [comment]
As reported by the above example (compiled & linked with a trivial go file to call C.PrintCVersion()):

```
C version: 201112
```

**Comment by zagrodzki** [comment]
Thanks. Can you check also how that same code behaves when you include libusb.h?

**Comment by zagrodzki** [comment]
Oh, and another one - clearly go build -n does not tell the whole truth about the build options. e.g. the gcc lines don't have libusb include paths from pkgconfig output. So perhaps there's more there.
Can you please run "go build -x github.com/kylelemons/gousb/usb" and paste the output?

**Comment by mikehamer** [comment]
```
$ go build -x 
WORK=/tmp/go-build543464353
mkdir -p $WORK/github.com/kylelemons/gousb/usb/_obj/
mkdir -p $WORK/github.com/kylelemons/gousb/
cd /home/idsc/go/src/github.com/kylelemons/gousb/usb
pkg-config --cflags libusb-1.0
pkg-config --libs libusb-1.0
CGO_LDFLAGS="-g" "-O2" "-lusb-1.0" /usr/local/go/pkg/tool/linux_arm/cgo -objdir $WORK/github.com/kylelemons/gousb/usb/_obj/ -importpath github.com/kylelemons/gousb/usb -- -I/usr/include/libusb-1.0 -I $WORK/github.com/kylelemons/gousb/usb/_obj/ -g -O2 constants.go error.go libusb.go
cd $WORK
gcc -fdebug-prefix-map=a=b -c trivial.c
gcc -gno-record-gcc-switches -c trivial.c
cd /home/idsc/go/src/github.com/kylelemons/gousb/usb
gcc -I . -fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK=/tmp/go-build -gno-record-gcc-switches -I/usr/include/libusb-1.0 -I $WORK/github.com/kylelemons/gousb/usb/_obj/ -g -O2 -o $WORK/github.com/kylelemons/gousb/usb/_obj/_cgo_export.o -c $WORK/github.com/kylelemons/gousb/usb/_obj/_cgo_export.c
gcc -I . -fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK=/tmp/go-build -gno-record-gcc-switches -I/usr/include/libusb-1.0 -I $WORK/github.com/kylelemons/gousb/usb/_obj/ -g -O2 -o $WORK/github.com/kylelemons/gousb/usb/_obj/constants.cgo2.o -c $WORK/github.com/kylelemons/gousb/usb/_obj/constants.cgo2.c
gcc -I . -fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK=/tmp/go-build -gno-record-gcc-switches -I/usr/include/libusb-1.0 -I $WORK/github.com/kylelemons/gousb/usb/_obj/ -g -O2 -o $WORK/github.com/kylelemons/gousb/usb/_obj/error.cgo2.o -c $WORK/github.com/kylelemons/gousb/usb/_obj/error.cgo2.c
gcc -I . -fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK=/tmp/go-build -gno-record-gcc-switches -I/usr/include/libusb-1.0 -I $WORK/github.com/kylelemons/gousb/usb/_obj/ -g -O2 -o $WORK/github.com/kylelemons/gousb/usb/_obj/libusb.cgo2.o -c $WORK/github.com/kylelemons/gousb/usb/_obj/libusb.cgo2.c
gcc -I . -fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK=/tmp/go-build -gno-record-gcc-switches -I/usr/include/libusb-1.0 -I $WORK/github.com/kylelemons/gousb/usb/_obj/ -g -O2 -o $WORK/github.com/kylelemons/gousb/usb/_obj/transfer.o -c ./transfer.c
gcc -I . -fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK=/tmp/go-build -gno-record-gcc-switches -I/usr/include/libusb-1.0 -I $WORK/github.com/kylelemons/gousb/usb/_obj/ -g -O2 -o $WORK/github.com/kylelemons/gousb/usb/_obj/_cgo_main.o -c $WORK/github.com/kylelemons/gousb/usb/_obj/_cgo_main.c
gcc -I . -fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK=/tmp/go-build -gno-record-gcc-switches -o $WORK/github.com/kylelemons/gousb/usb/_obj/_cgo_.o $WORK/github.com/kylelemons/gousb/usb/_obj/_cgo_main.o $WORK/github.com/kylelemons/gousb/usb/_obj/_cgo_export.o $WORK/github.com/kylelemons/gousb/usb/_obj/constants.cgo2.o $WORK/github.com/kylelemons/gousb/usb/_obj/error.cgo2.o $WORK/github.com/kylelemons/gousb/usb/_obj/libusb.cgo2.o $WORK/github.com/kylelemons/gousb/usb/_obj/transfer.o -g -O2 -lusb-1.0 -pie
/usr/local/go/pkg/tool/linux_arm/cgo -dynpackage usb -dynimport $WORK/github.com/kylelemons/gousb/usb/_obj/_cgo_.o -dynout $WORK/github.com/kylelemons/gousb/usb/_obj/_cgo_import.go
cd $WORK
gcc -no-pie -c trivial.c
cd /home/idsc/go/src/github.com/kylelemons/gousb/usb
gcc -I . -fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK=/tmp/go-build -gno-record-gcc-switches -o $WORK/github.com/kylelemons/gousb/usb/_obj/_all.o $WORK/github.com/kylelemons/gousb/usb/_obj/_cgo_export.o $WORK/github.com/kylelemons/gousb/usb/_obj/constants.cgo2.o $WORK/github.com/kylelemons/gousb/usb/_obj/error.cgo2.o $WORK/github.com/kylelemons/gousb/usb/_obj/libusb.cgo2.o $WORK/github.com/kylelemons/gousb/usb/_obj/transfer.o -g -O2 -Wl,-r -nostdlib -no-pie -Wl,--build-id=none
/usr/local/go/pkg/tool/linux_arm/compile -o $WORK/github.com/kylelemons/gousb/usb.a -trimpath $WORK -p github.com/kylelemons/gousb/usb -buildid fbd3d1741d25b00daebdb54f73e8f43bb4ce183d -D _/home/idsc/go/src/github.com/kylelemons/gousb/usb -I $WORK -pack ./config.go ./debug.go ./descriptor.go ./device.go ./endpoint.go ./misc.go ./transfer.go ./usb.go $WORK/github.com/kylelemons/gousb/usb/_obj/_cgo_gotypes.go $WORK/github.com/kylelemons/gousb/usb/_obj/constants.cgo1.go $WORK/github.com/kylelemons/gousb/usb/_obj/error.cgo1.go $WORK/github.com/kylelemons/gousb/usb/_obj/libusb.cgo1.go $WORK/github.com/kylelemons/gousb/usb/_obj/_cgo_import.go
# github.com/kylelemons/gousb/usb
./libusb.go:362[/tmp/go-build543464353/github.com/kylelemons/gousb/usb/_obj/libusb.cgo1.go:584]: _Ctype_struct_libusb_transfer literal.iso_packet_desc undefined (type _Ctype_struct_libusb_transfer has no field or method iso_packet_desc)
```

I have also tried using GCC 6.2, which shows the same behaviour.

**Comment by mikehamer** [comment]
```go
package main

/*
#cgo pkg-config: libusb-1.0
#include <libusb.h>
#include "c_version.h"
*/
import "C"

func main() {
	C.PrintCVersion()
}
```
results in the same output as when `libusb.h` is not included:
```
C version: 201112
```

**Comment by zagrodzki** [comment]
right. At this point I don't think it's gcc at all. In fact the "go build" output would seem to confirm it - the gcc compilations work fine, it's only the pre-processed Go-with-C code that looks off.

I ran this sequence:
WORK=/tmp/go-build565712256
mkdir -p $WORK/github.com/kylelemons/gousb/usb/_obj/
CGO_LDFLAGS="-g -O2 -lusb-1.0" /home/sebek/go/pkg/tool/linux_amd64/cgo -objdir $WORK/github.com/kylelemons/gousb/usb/_obj/ -importpath github.com/kylelemons/gousb/usb -- -I/usr/include/libusb-1.0 -I $WORK/github.com/kylelemons/gousb/usb/_obj/ constants.go error.go libusb.go

and the resulting /tmp/go-build565712256/github.com/kylelemons/gousb/usb/_obj/_cgo_gotypes.go has this:

type _Ctype_struct_libusb_transfer struct {                                     
//line :1                                                                       
    dev_handle  *_Ctype_struct_libusb_device_handle                             
//line :1                                                                       
    flags       _Ctype_uint8_t                                                  
//line :1                                                                       
    endpoint    _Ctype_uchar                                                    
//line :1                                                                       
    _type       _Ctype_uchar                                                    
//line :1                                                                       
    _       [1]byte                                                             
//line :1                                                                       
    timeout     _Ctype_uint                                                     
//line :1                                                                       
    status      uint32                                                          
//line :1                                                                       
    length      _Ctype_int                                                      
//line :1                                                                       
    actual_length   _Ctype_int                                                  
//line :1                                                                       
    _       [4]byte                                                             
//line :1                                                                       
    callback    _Ctype_libusb_transfer_cb_fn                                    
//line :1                                                                       
    user_data   unsafe.Pointer                                                  
//line :1                                                                       
    buffer      *_Ctype_uchar                                                   
//line :1                                                                       
    num_iso_packets _Ctype_int                                                  
//line :1                                                                       
    iso_packet_desc [0]_Ctype_struct_libusb_iso_packet_descriptor               
//line :1                                                                       
    _       [4]byte                                                             
//line :1                                                                       
}                                                                               

Can you see how it looks in your case? (you might need to update tool paths from /home/sebek... in the commans above).

**Comment by mikehamer** [comment]
Running the equivalent yields:

```go
type _Ctype_struct_libusb_transfer struct {
	dev_handle	*_Ctype_struct_libusb_device_handle
	flags		_Ctype_uint8_t
	endpoint	_Ctype_uchar
	_type		_Ctype_uchar
	_		[1]byte
	timeout		_Ctype_uint
	status		uint32
	length		_Ctype_int
	actual_length	_Ctype_int
	callback	_Ctype_libusb_transfer_cb_fn
	user_data	unsafe.Pointer
	buffer		*_Ctype_uchar
	num_iso_packets	_Ctype_int
}
```

And if I patch the flexible array members to [1] (such that the go build succeeds):

```go
type _Ctype_struct_libusb_transfer struct {
	dev_handle	*_Ctype_struct_libusb_device_handle
	flags		_Ctype_uint8_t
	endpoint	_Ctype_uchar
	_type		_Ctype_uchar
	_		[1]byte
	timeout		_Ctype_uint
	status		uint32
	length		_Ctype_int
	actual_length	_Ctype_int
	callback	_Ctype_libusb_transfer_cb_fn
	user_data	unsafe.Pointer
	buffer		*_Ctype_uchar
	num_iso_packets	_Ctype_int
	iso_packet_desc	[1]_Ctype_struct_libusb_iso_packet_descriptor
}
```

**Comment by zagrodzki** [comment]
ok. So it seems like cgo is at fault. And it looks like it's doing it's own preprocessing of the .h files rather than deferring to gcc/cpp, which would explain the missing __STDC_VERSION__ define.
And it seems the processing is different between arm and x86_64. I'm taking a look at cgo source...

**Comment by mikehamer** [comment]
However, there is a `__STDC_VERSION__` defined during the preprocessing, since the following update has to be made for compilation to succeed.

From:
```c
/** Isochronous packet descriptors, for isochronous transfers only. */
struct libusb_iso_packet_descriptor iso_packet_desc
#if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901L)
        [] // <----- THIS LINE MUST BE CHANGED TO [1]
#else
        [0] /* non-standard, but usually working code */
#endif
```
to:
```c
/** Isochronous packet descriptors, for isochronous transfers only. */
struct libusb_iso_packet_descriptor iso_packet_desc
#if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901L)
        [1] /* valid C99 code */
#else
        [0] /* non-standard, but usually working code */
#endif
```

**Comment by mikehamer** [comment]
Confirmed with the following minimal example (unrelated to libusb or this gousb):
```go
package main

import (
	"fmt"
	"unsafe"
)

/*
struct test {
	int a;
	int testmember[];
};
*/
import "C"

func main() {
	fmt.Println(unsafe.Offsetof(C.struct_test{}.testmember))
}
```
resulting in:
```
$ go run main.go
# command-line-arguments
./main.go:17: C.struct_test literal.testmember undefined (type C.struct_test has no field or method testmember)
```
If `[]` is changed to `[1]`, the result is the expected `4`

**Comment by zagrodzki** [comment]
I see. I understood that you need to change [0] to [1] in order to make things. So that means you didn't actually apply the darwin fix (which replaces [0] with [1]), but updated libusb.h by hand?

cgo has this in the documentation (https://golang.org/cmd/cgo/):

> Go code cannot refer to zero-sized fields that occur at the end of non-empty C structs. To get the address of such a field (which is the only operation you can do with a zero-sized field) you must take the address of the struct and add the size of the struct.

....

aaaargs, I think I found it. I think it's because of memory alignment. See these two examples:

```
/*
struct foo {
		int x;
		char y[];
};
*/
import "C"
import "fmt"

var (
	Y *C.struct_foo
)

func Foo() {
	fmt.Println(Y.y)
}
```

gives me:
Y.y undefined (type *C.struct_foo has no field or method y)

Now I modify the struct:
```
struct foo {                                                                    
        int x;                                                                  
        char padding;                                                           
        char y[];                                                               
};                                                                              
```

tadaam, magic, it works. It looks like the zero-field is ignored if the zero-lenght field is aligned on the boundary of whatever gcc decided to allocate for the struct. And if gcc decided to pad the struct size, suddenly it's no longer considered a zero-length field.

I'll update gousb to not rely on the zero-lenght field.

**Comment by zagrodzki** [comment]
and in fact that will be trivial, since all isochronous packet handling happens in the C code and the iso packet reference is not used anywhere.

**Comment by zagrodzki** [comment]
I pushed https://github.com/kylelemons/gousb/commit/7c8d79ed6a96a66fcf6a465ffb68be617bbb442e
Can you check if it solves your issue?

**Comment by mikehamer** [comment]
This solves the issue. Thank you :-)

**Comment by zagrodzki** [comment]
I filed https://github.com/golang/go/issues/20275 for Go. I think the fields should never be visible rather than indeterministically. That would have saved us some time here.
