### ISSUE TITLE
Appveyor build

### ISSUE THREAD

**Issue by half2me** [kylelemons/gousb#51]
I'm trying to build a project that uses this library, and I need it to compile on windows.
Do you think it would be possible to add an appveyor build to this repo, so running on windows could be tested, and also give us some idea of how to build our own projects?

I did a `choco install pkgconfiglite`
but I'm completely lost when installing libusb. I have no idea where to put the headers, libs, etc.

**Comment by zagrodzki** [comment]
If it's ok for you to compile within mingw environment, this is how to do it:

choco install mingw msys2
run mingw64.exe, and inside mingw64 console:
pacman -S mingw64/mingw-w64-x86_64-go mingw64/mingw-w64-x86_64-gcc 
mingw64/mingw-w64-x86_64-pkg-config mingw64/mingw-w64-x86_64-libusb msys/git
go get github.com/google/gousb/lsusb

You'll need to include "libusb-1.0.dll" with your program.

Does that work for you?

As a side note, I'll allow myself to express my disappointment in Windows Server Core - I hoped for a server that can be managed from a commandline. Instead it's a trimmed version of desktop, which makes for a really weird experience. Ugh.

**Comment by half2me** [comment]
@zagrodzki Thanks for the help, I'll try today. AppVeyor should have mingw and msys2 already installed, but If I get it to work, I can contribute with a .appveyor.yml file

**Comment by zagrodzki** [comment]
This package is now deprecated, version 2.0 of the API is available under github.com/google/gousb.
Please create any new pull requests in the new API. Thanks!

**Comment by half2me** [comment]
@zagrodzki I get this when I run it on appVeyor, but locally it works perfectly thanks!:
C:\msys64\mingw64\lib\go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
/usr/lib/gcc/x86_64-pc-msys/6.3.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lmingwex
/usr/lib/gcc/x86_64-pc-msys/6.3.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lmingw32
collect2: error: ld returned 1 exit status

Dunno why its trying to link to a 32bit?

**Comment by zagrodzki** [comment]
What does your "go version" show?

**Comment by zagrodzki** [comment]
nvm, it's probably x86_64 - based on appveyor docs, the default c:\go is x86_64.

This might be relevant: https://stackoverflow.com/questions/37497354/compile-cgo-lib-on-cygwin64-ld-cannot-find-lmingw32

But otherwise, I have no idea. I don't understand all these relations between cygwin, mingw and msys...

**Comment by zagrodzki** [comment]
is it possible that go is finding the gcc path from cygwin, rather than from mingw64? Does that appveyor worker have mingw-w64-x86_64-gcc installed?

**Comment by half2me** [comment]
@zagrodzki it does, but funny when I completely reinstall msys2 and mingw, it seems to compile

**Comment by zagrodzki** [comment]
Maybe PATH component order plays a role here? perhaps after reinstallation, the msys2/mingw paths are moved to a position that makes them preferred?

**Comment by half2me** [comment]
yes, the order of the PATHs, had to be changed, builds seem to be working now, thanks a lot :)

**Comment by zagrodzki** [comment]
Glad to hear that. Please create a pull request to the new repository (github.com/google/gousb) with the appveyor.yml that you used.

**Comment by half2me** [comment]
@zagrodzki Sure! I'll just clean it up a bit first. Should I run the same unit tests as in the .travis file?

**Comment by zagrodzki** [comment]
No, in Travis we run things like lint/vet/coverage reports, and we don't need to duplicate them on Appveyor, I think.
So it would be enough to add an equivalent of "go test ./..." in Appveyor, that would be sufficient.

**Comment by half2me** [comment]
@zagrodzki okay, I'll have this ready soon
