### ISSUE TITLE
Deprecation notice

### ISSUE THREAD

**Issue by zagrodzki** [kylelemons/gousb#52]
Fork owners: @karalabe @truveris @jpoirier @giddyinc @yokujin @half2me @peronix @nkovacs @thorduri @d3v1l401 @arcanericky @dominikh @shenshouer @zhfuzzy @mgenov @yne717 @diocles @dcarley @2sidedfigure @datastream @yukkeorg @baloo @ebfe @mevers47 @pjvds 

You're receiving this notice because at some point you created a fork of github.com/kylelemons/gousb. This is a deprecation notice of that package. The new API is available under github.com/google/gousb.

Thanks!

**Comment by half2me** [comment]
Thanks @zagrodzki but unfortunately I have problems with the new version: https://github.com/kylelemons/gousb/issues/54
