### ISSUE TITLE
Endpoint problem

### ISSUE THREAD

**Issue by half2me** [kylelemons/gousb#54]
I tried the new /google/gousb, I used to be able to do this:
`epRead, err := dev.OpenEndpoint(1, 0, 0, uint8(1)|uint8(usb.ENDPOINT_DIR_IN))`
`epWrite, err := dev.OpenEndpoint(1, 0, 0, uint8(1)|uint8(usb.ENDPOINT_DIR_OUT))`

Now with the new interface when I do this:
`epRead, err := dev.intf.InEndpoint(1)`
`epWrite, err := dev.intf.OutEndpoint(1)`

It gives me this error:
`ep #1 OUT (address 0x01) bulk [64 bytes] is not an IN endpoint`

**Comment by zagrodzki** [comment]
Ok. That seems unexpected - effectively you're saying that you have the same endpoint number as both an IN and an OUT endpoint? i.e. 0x01 and 0x81? My understanding was that this was not allowed by the USB standard - the endpoint number (in this case, 0x01 for both) is unique, and the 0x80 is only a flag indicating the direction of that endpoint.

What is the device that you're using? Can you show me the result of "lsusb -v" on it?

**Comment by zagrodzki** [comment]
FTR, this is the bit that I relied on, part of USB2.0 spec:

Term definitions from chapter 2:
Endpoint Number: A four-bit value between 0H and FH, inclusive, associated with an endpoint on
a USB device
Endpoint Address The combination of an endpoint number and an endpoint direction on a USB
device. Each endpoint address supports data transfer in one direction.

5.3.1
[...] Each endpoint on a device is given at design time a unique device-determined identifier called the endpoint number. Each endpoint has a device-determined direction of data flow. [...]

From that I took that a unique identifier, i.e. endpoint number, means that you can't have two endpoints with the same number, even if they have different addresses (i.e. directions). 

That being said, the wikibook on "SerialProgramming/USB" has this bit:

These endpoints (and their respective pipes) are numbered 0-15 in each direction, so a device/function can have up to 32 active pipes, 16 into the host controller and 16 out of the controller.

which means an endpoint is uniquely identified not by it's number, but it's address, and two endpoints with the same number are possible. I haven't seen devices like that, but in theory I understand they would be possible?

If you have at least one example of a device like that, then it's clearly a problem with our assumptions.

**Comment by zagrodzki** [comment]
some more googling seems to confirm that it's indeed the endpoint address that is unique, not endpoint number, so I'm starting to write a fix anyway...

**Comment by zagrodzki** [comment]
I'm addressing this issue in https://github.com/google/gousb/pull/1

**Comment by half2me** [comment]
I'm using an ANT+ dongle from dynastream. I'm working on a mac, so no `lsusb`
But here is my project, where you can see the master branch has working code, and my other branch which uses the new v2 API of gousb, that doesn't as it only recognises 1 EP, as an output
https://github.com/half2me/antgo

**Comment by half2me** [comment]
I'm not really up on the standards of USB? I just used some example code I found and they would always just use EP 1 for everything

**Comment by half2me** [comment]
On osx I run `ioreg -p IOUSB -l -w 0` it gives me this:
```
+-o ANT USBStick2@14200000  <class AppleUSBDevice, id 0x100007cd9, registered, matched, active, busy 0 (8 ms), retain 14>
        {
          "sessionID" = 295531346797714
          "iManufacturer" = 1
          "bNumConfigurations" = 1
          "idProduct" = 4104
          "bcdDevice" = 256
          "Bus Power Available" = 250
          "USB Address" = 26
          "bMaxPacketSize0" = 32
          "iProduct" = 2
          "iSerialNumber" = 3
          "bDeviceClass" = 0
          "Built-In" = No
          "locationID" = 337641472
          "bDeviceSubClass" = 0
          "bcdUSB" = 512
          "USB Product Name" = "ANT USBStick2"
          "PortNum" = 2
          "non-removable" = "no"
          "IOCFPlugInTypes" = {"9dc7b780-9ec0-11d4-a54f-000a27052861"="IOUSBFamily.kext/Contents/PlugIns/IOUSBLib.bundle"}
          "bDeviceProtocol" = 0
          "IOUserClientClass" = "IOUSBDeviceUserClientV2"
          "IOPowerManagement" = {"DevicePowerState"=0,"CurrentPowerState"=3,"CapabilityFlags"=65536,"MaxPowerState"=4,"DriverPowerState"=3}
          "kUSBCurrentConfiguration" = 1
          "Device Speed" = 1
          "USB Vendor Name" = "Dynastream Innovations"
          "idVendor" = 4047
          "IOGeneralInterest" = "IOCommand is not serializable"
          "USB Serial Number" = "169"
          "IOClassNameOverride" = "IOUSBDevice"
        }
```

**Comment by zagrodzki** [comment]
This output does not include defined endpoints, so it's not that useful. But I'll assume that this is the same device as listed in http://www.spinics.net/lists/linux-usb/msg90227.html, and that one shows:

    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              2 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1

i.e. it confirms that the device has the same endpoint number (1) used twice, once for IN and once for OUT. So apparently, despite USB spec saying "numbers are unique", it really means "addresses are unique". And in fact USB 3.0 spec defines the "address triple"  as the endpoint identifier, where address triple is device+endpoint+direction. So it all sounds correct, and the code is wrong. A pull req with a fix was created, feel free to pull it from a branch and try it out.

**Comment by half2me** [comment]
Thank you very much, I will try tomorrow! You have been a big help!

**Comment by zagrodzki** [comment]
@half2me I didn't see another issue opened for the "unknown error" problem that you've reported on the deprecation thread. Did you find the cause of the problem, or is it still an issue?

**Comment by half2me** [comment]
@zagrodzki it is still an issue, I just haven't had much time lately to follow up on it. I'll open an issue soon
